dry-run: null
hookfiles: null
sandbox: false
server: bundle exec rails server
server-wait: 3
init: false
custom:
  apiaryApiKey: add0b5027298ac11e76d09ccb2032d49
  apiaryApiName: dreddinittest
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: "http://localhost:3000"
